language: node_js

sudo: required

node_js:
  - v10.8.0

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - williamstowersdev@gmail.com
    on_success: never
    on_failure: always

services:
  - redis-server

script:
  - npm install
  - npm run lint
  - npm run build
  - npm link
  - nqr -a examples/redis.yml -l /home/travis/build/williamsdevaccount/enqueuer-plugin-redis
